# =======================================================================================
# NGINX REVERSE PROXY & ROUTING CONFIGURATION
# =======================================================================================
# This file acts as the primary ingress control for the microservices architecture. 
# It serves static frontend assets directly and securely forwards all incoming API traffic 
# to internal backend containers using the network's built-in DNS service discovery.
# =======================================================================================


# Defines a named group of backend servers that Nginx can route traffic to, enabling load balancing and scaling of the reservation service.
upstream reservation_api{
    server reservation-service:8080;        # todo: remember it must match docker-compose service name
}

server {
    listen 80;

    location / {

        # Serve the frontend SPA / static files
        root /usr/share/nginx/html;
        index index.html;

        # Core directive for Single Page Applications (SPA) and client-side routing.
        # It checks for the existence of files in the following order:
        # 1) $uri  : Looks for an exact physical file matching the request (e.g., /css/main.css).
        # 2) $uri/ : Looks for a directory matching the request.
        # 3) /index.html : The fallback. If neither a file nor a directory is found, Nginx skips
        #    throwing a 404 error and serves index.html instead.
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api calls to the Java backend
    location /api/ {
        proxy_pass         http://reservation_api;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }

    # Block any direct browser access to internal health/metrics endpoints
    location ~ ^/(actuator|metrics) {
        deny all;
        return 404;
    }

}
