# let Nginx scale automatically based on the number of available CPU cores.
worker_processes auto;

events {
    # keep this low for our lightweight container to save memory.
    # in production/AKS we will bump this significantly (e.g., 1024).
    worker_connections 20;
}

http {
    # maps file extensions to correct internet media types (CSS, JS, etc.)
    include         /etc/nginx/mime.types;
    
    # fallback type for binary data if the file extension is unknown.
    default_type    application/octet-stream;

    # speed booster: copies data between file descriptors directly within the 
    # kernel space, bypassing the user-space buffer completely. Efficient for static files.
    sendfile        on;

    # modular approach: dynamically injects server block configs 
    include /etc/nginx/conf.d/*.conf;
}